import Navbar from "@/components/navbar/Navbar";
import "./globals.css";

import { Inter, Poppins, Roboto } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], variable: "--font-inter" });
const roboto = Roboto({ subsets: ['latin'], weight: ["100","300","400","500","700","900"], variable: "--font-roboto" });
const poppins = Poppins({ subsets: ['latin'], weight: ["100","300","400","500","700","900"], variable: "--font-poppins" });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${roboto.variable} ${poppins.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
